version: '2.0'
services:
  url-shortener:
    environment:
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8
    build: url-shortener/
    working_dir: "/opt/url-shortener"
    command: bash -c "python run.py --port 80 -c production"
    ports:
      - "80:80"
    links:
      - db
  db:
    image: mongo
